### ISSUE TITLE
CA_CERT_PARAMS[@]: unbound variable

### ISSUE THREAD

**Issue by Anil8753** [softwaremill/fablo#210]
./fabrica up fails at CA_CERT_PARAMS[@]: unbound variable

```
Packaging chaincode chaincode1...
   CHAINCODE_VERSION: 0.0.1 
   CHAINCODE_LANG: node 
   PEER_ADDRESS: peer0.org1.com:7060 
   CLI_NAME: cli.org1.com 
Installing chaincode chaincode1...
   CHAINCODE_VERSION: 0.0.1 
   PEER_ADDRESS: peer0.org1.com:7060 
   CA_CERT:  
/Users/anikumar/Development/MyProjets/TS/Cello/fabrica2.x/fabrica-target/fabric-docker/scripts/chaincode-functions.sh: line 81: CA_CERT_PARAMS[@]: unbound variable
```

Also listing of installed channel does not show any output.
```
anikumar@anikumars-MacBook-Pro fabrica2.x % docker exec -e CORE_PEER_ADDRESS="peer0.org1.com:7060" "cli.org1.com" peer chaincode list --installed
Get installed chaincodes on peer:
```
