### ISSUE TITLE
[question] using fablo in a multi-node network

### ISSUE THREAD

**Issue by elhpavtat** [softwaremill/fablo#231]
Hello!

Can you tell me if I can use fablo to deploy to multiple nodes (virtual machines) and what is the best way to do it?
As I understand it, I need in the channels section just to add peers. But how do I correctly specify IP addresses of my virtual machines?
```
  - name: my-channel1
    orgs:
      - name: org1
        peers:
          - peer0
          - peer1
          - peer2
```

Another question, is it enough to use one configuration file for all nodes?
I have a non-standard topology:
one organisation and 5 nodes (VMs).
hlf version 2.3.3, raft + TLS + leveldb
I will start developing chaincode after network deployment.

Thank you so much.
